### ISSUE TITLE
If it's "ROM to ELF convertor", then why binary file is called "iram"?

### ISSUE THREAD

**Issue by pfalcon** [jcmvbkbc/esp-elf-rom#1]
subj.

**Comment by jcmvbkbc** [comment]
It's the name given to it by kongo, who published the dump, here: http://www.esp8266.com/viewtopic.php?f=6&t=39&hilit=iram0.bin&start=10#p327

**Comment by pfalcon** [comment]
Well, I know the story not worse than you, I watched it those early days closely ;-). So, let me be explicit: kongo at that time didn't know (or care) what it is, but currently it's well known, and it's known that "iram" is something completely different, so  maybe it's time to rename it? ;-)

**Comment by jcmvbkbc** [comment]
May be. Still wondering why it matters.

**Comment by pfalcon** [comment]
Well, https://github.com/tommie/lx106-hal/issues/1#issuecomment-96367093 mentioned elsewhere gives a hint: either stuff's getting done in a way to make it easy for other folks to learn from it and continue from there, or it's done in a way to confuse folks, then they will likely spin for awhile on it without progress, possibly leaving in frustration.

Ah, and yeah, I'm looking for a good trusty location of ROM file to reference as needed.

**Comment by pfalcon** [comment]
Thanks for (well, partial) fix ;-)

**Comment by jcmvbkbc** [comment]
> Thanks for (well, partial) fix

I think it'd be much easier for us both if you minimize the amount of guesswork on my part when you have something particular in mind. What's missing?

**Comment by pfalcon** [comment]
Well, so looking at esp8266.ld:

```
    dport0_0_seg : org = 0x3ff00000, len = 0x10
    dram0_0_seg :  org = 0x3ffe8000, len = 0x14000
    iram1_0_seg :  org = 0x40100000, len = 0x8000
    irom0_0_seg :  org = 0x40210000, len = 0x5A000
```

irom0 there is what's at 0x40210000, then calling something which is as 0x40000000 also "irom0" is just another source of confusion. "rom" is too generic, though maybe "rom0" is good enough. But usually people call it "bootrom" or "maskrom". I'm sure you'd know better how exactly to call it, but people will surely use that as reference, so avoiding any mix-ups would help much.

**Comment by jcmvbkbc** [comment]
You're right, I didn't think about linker map. And there's no entry for ROM in it. OK, will call it bootrom.bin

**Comment by pfalcon** [comment]
Thanks!
